language: java

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

branches:
  # only:
  #   master
# for deploy using tag commit
# we need except all beyond master and tag
# will not deploy if only: master
  except:
    - develop
    - gh-pages
#git flow branches following
    - 'feature/*'
    - 'hotfix/*'
    - 'release/*'

install:
  - mvn install
  - mvn -P full install

deploy:
  - provider: releases
    api_key: '$GITHUB_API_KEY' #refer to travis environment varible setting
    file_glob: true
    file: "output/*.jar" #JComicDownload-v5.30.jar JComicDownload-v5.30-FULL.jar
    skip_cleanup: true
    on:
      tags: true

  # - provider: pages
  #   api_key: '$GITHUB_API_KEY' #refer to travis environment varible setting
  #   file_glob: true
  #   file: "target/*.jar" #JComicDownload-v5.30.jar
  #   skip_cleanup: true
  #   on:
  #     tags: true
